apiVersion: v2
appVersion: 1.2.0
description: A Helm chart to deploy Grey Matter Fabric
name: fabric
version: 2.2.1
home: https://greymatter.io
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: greymatter-io
    email: engineering@greymatter.io
keywords:
  - Grey Matter
  - service mesh
  - fabric
dependencies:
  - name: control-api
    repository: file://./control-api
    version: '2.2.4'

  - name: control
    repository: file://./control
    version: '2.2.3'

  - name: jwt
    repository: file://./jwt
    version: '2.2.3'

  - name: redis
    repository: file://./redis
    version: '1.0.2'
    condition: global.external_redis.disabled
    alias: mesh-redis
