{{- if not .Values.postgres.rds.enabled }}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgres-slo
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.global.control.cluster_label }}: postgres-slo
spec:
  serviceName: postgres-slo
  selector:
    matchLabels:
      {{ .Values.global.control.cluster_label }}: postgres-slo
  replicas: {{ .Values.postgres.replica_count }}
  serviceName: postgres-slo
  template:
    metadata:
      labels:
        {{ .Values.global.control.cluster_label }}: postgres-slo
    spec:
      # Security context for openshift, kubernetes and eks is the same. 

      securityContext:
        runAsUser: 2000
        runAsGroup: 0
        fsGroup: 2000
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        imagePullPolicy: {{ .Values.postgres.image_pull_policy }}
        {{- if .Values.postgres.resources }}
        resources:
{{ toYaml .Values.postgres.resources | indent 10 }}
        {{- end }}
        ports:
          - name: postgres
            containerPort: 5432
        env:
        {{- include "envvars" (dict "envvar" .Values.postgres.envvars "top" $) | indent 10 }}
        volumeMounts:
          - name: data
            mountPath: {{ .Values.postgres.data_mount_point }}
        {{- if .Values.postgres.secret.enabled }}
          - name: certificates
            mountPath: {{ .Values.postgres.secret.mount_point }}
          - name: postgres-slo-config
            mountPath: {{ .Values.postgres.conf_mount_point }}
          - name: postgres-slo-overrides
            mountPath: {{ .Values.postgres.overrides_mount_point }}
        {{- end }}
        readinessProbe:
          tcpSocket:
            port: postgres
          # Pods are considered to be in a Failure state before the initialDelaySeconds has passed, meaning they won't be backends for a service
          initialDelaySeconds: 5
          periodSeconds: 2
      {{- if .Values.postgres.private_image }}
      imagePullSecrets:
      - name: {{ .Values.global.image_pull_secret }}
      {{- end }} 
      volumes:
      - name: postgres-slo-config
        configMap:
          name: postgres-slo-config
      - name: postgres-slo-overrides
        configMap:
          name: postgres-slo-overrides
      {{- if .Values.postgres.secret.enabled }}
      - name: certificates
        secret:
          {{- if .Values.global.global_certs.enabled }}
          secretName: global-certs
          {{- else }}
          secretName: {{ .Values.postgres.secret.secret_name }}
          {{- end }}
          # If you do not spedify, default is 644. Postgres crashes and burns if it's readable by the world.
          defaultMode: 0640
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
{{- end }}
