{{- define "registry_auths" }}
{{- $creds := dict "credentials" (list) }}
{{- range $repo := .Values.dockerCredentials }}
{{- $registry := $repo.registry }}
{{- $email := $repo.email }}
{{- $username:= $repo.username }}
{{- $password := $repo.password }}
{{- $b64auth :=  (printf "%s:%s" $username $password | b64enc) }}
{{- $autho := (printf "\"%s\": {\"auth\": \"%s\"}" $registry $b64auth) | append $creds.credentials | set $creds "credentials" }}
{{- end }}
{{- $authos := (join "," $creds.credentials) }}
{{- printf $authos }}
{{- end }}

{{- $imagePullSecret := (lookup "v1" "Secret" .Release.Namespace .Values.global.image_pull_secret) }}
{{- if not $imagePullSecret }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.global.image_pull_secret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {%s}}" (include "registry_auths" .) | b64enc }}
{{/* --- */}}
{{- end }}