{{ with .Values.redis }}
{{ $redisPassword := "" }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
  {{- $redisPassword = index $secret.data.password | b64dec }}
{{- else }}
  {{ if eq .password "" }}
    {{ $redisPassword = (randAlpha 32) }}
  {{ else }}
    {{ $redisPassword = .password }}
  {{ end }}
{{ end }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  password: {{ $redisPassword }}
{{ end }}