{{- if .Values.sidecar.create_sidecar_secret }}
{{ if .Values.sidecar.certificates }}
{{- with .Values.sidecar.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.pem: {{ .ca | b64enc }}
  ca_b64: {{ .ca | b64enc | b64enc }}
  cert.pem: {{ .cert | b64enc }}
  cert_b64: {{ .cert | b64enc | b64enc }}
  key.pem: {{ .key | b64enc }}
  key_b64: {{ .key | b64enc | b64enc }}
{{- end }}
{{- end }}
{{- end }}
