kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgres-slo
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-slo
spec:
  selector:
    matchLabels:
      app: postgres-slo
  replicas: {{ .Values.postgres.replica_count }}
  serviceName: postgres-slo
  template:
    metadata:
      labels:
        app: postgres-slo
    spec:
      containers:
      - name: postgres
        {{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}
        image: {{ .Values.postgres.openshift.image }}
        {{- else }}
        image: {{ .Values.postgres.k8s.image }}
        {{- end }}
        imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
        {{- if .Values.postgres.resources }}
        resources:
{{ toYaml .Values.postgres.resources | indent 10 }}
        {{- end }}
        ports:
          - name: postgres
            containerPort: 5432
        env:
      {{- range $envvar := .Values.postgres.envvars }}
        {{- $envName := tpl $envvar.name $ | upper | replace "." "_" | replace "-" "_" }}
        {{- if eq $envvar.type "secret" }}
          - name: {{ $envName }}
            valueFrom:
              secretKeyRef:
                name: {{ $envvar.secret }}
                key: {{ $envvar.key }}
        {{- else if eq $envvar.type "value" }}
          - name: {{ $envName }}
            value: {{ $envvar.value | quote }}
        {{- end }}
      {{- end  }}
        volumeMounts:
          - name: postgres-slo
            mountPath: {{ .Values.postgres.data_mount_point }}
        {{- if .Values.postgres.ssl.enabled }}
          - name: certificates
            mountPath: {{ .Values.postgres.ssl.mountPoint }}
          - name: postgres-slo-config
            mountPath: {{ .Values.postgres.confMountPoint }}
          - name: postgres-slo-overrides
            mountPath: {{ .Values.postgres.overridesMountPoint }}
        {{- end }}
        readinessProbe:
          tcpSocket:
            port: postgres
          # Pods are considered to be in a Failure state before the initialDelaySeconds has passed, meaning they won't be backends for a service
          initialDelaySeconds: 5
          periodSeconds: 2
      {{- if .Values.postgres.private_image }}
      imagePullSecrets:
      - name: docker.secret
      {{- end }}
      volumes:
      - name: postgres-slo
        persistentVolumeClaim:
          claimName: postgres-slo
      - name: postgres-slo-config
        configMap:
          name: postgres-slo-config
      - name: postgres-slo-overrides
        configMap:
          name: postgres-slo-overrides
      {{- if .Values.postgres.ssl.enabled }}
      - name: certificates
        secret:
          secretName: {{ .Values.postgres.ssl.name }}
          defaultMode: 0400
      {{- end }}
