---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fibonacci-test
    greymatter.io/control: fibonacci-test-ns
  name: fibonacci-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci-test
      greymatter.io/control: fibonacci-test-ns
  template:
    metadata:
      labels:
        app: fibonacci-test
        greymatter.io/control: fibonacci-test-ns
    spec:
      containers:
        - name: fibonacci-test
          image: docker.greymatter.io/internal/fibonacci:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
        - name: sidecar
          image: "docker.greymatter.io/development/gm-proxy:1.4.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 8081
            - name: proxy
              containerPort: 10808
          env:
            - name: ENVOY_ADMIN_LOG_PATH
              value: "/dev/stdout"
            - name: PROXY_DYNAMIC
              value: "true"
            - name: XDS_CLUSTER
              value: "fibonacci-test"
            - name: XDS_HOST
              value: "control.default.svc"
            - name: XDS_NODE_ID
              value: "default"
            - name: XDS_PORT
              value: "50000"
            - name: XDS_ZONE
              value: "zone-default-zone"
      imagePullSecrets:
        - name: docker.secret