{{- if .Values.edge.create_edge_secret }}
{{ if .Values.edge.certificates }}
{{- with .Values.edge.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.pem: {{ .ca | b64enc }}
  ca_b64: {{ .ca | b64enc | b64enc }}
  server.crt: {{ .cert | b64enc }}
  cert_b64: {{ .cert | b64enc | b64enc }}
  server.key: {{ .key | b64enc }}
  key_b64: {{ .key | b64enc | b64enc }}
{{- end }}
{{- end }}
{{- end }}
