apiVersion: v1
appVersion: 1.0.2-dev
description: A Helm chart to deploy Grey Matter
name: greymatter
version: 2.0.1-dev
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: Decipher Technology Studios Engineering
    email: engineering@deciphernow.com
    website: deciphernow.com
keywords:
  - Grey Matter
  - service mesh
