dependencies:
- name: dashboard
  version: "1.0.0"
  repository: "file://../dashboard"

- name: catalog
  version: "1.0.0"
  repository: "file://../catalog"

- name: xds
  version: "1.0.0"
  repository: "file://../xds"

- name: edge
  version: "1.0.0"
  repository: "file://../edge"

- name: data
  version: "1.0.0"
  repository: "file://../data"

- name: jwt
  version: "1.0.0"
  repository: "file://../jwt"

- name: slo
  version: "1.0.0"
  repository: "file://../slo"
