apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: {{ .Values.global.spire.namespace }}
  labels:
    app: agent
    cluster: spire.agent
spec:
  selector:
    matchLabels:
      app: agent
      gmproxy: agent
      cluster: spire.agent
  template:
    metadata:
      namespace: {{ .Values.global.spire.namespace }}
      labels:
        gmproxy: agent
        app: agent
        cluster: spire.agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: agent
      initContainers:
        - name: init-server
          image: gcr.io/spiffe-io/wait-for-it
          args:
            - "-t"
            - "30"
            - "server:8443"
        - name: init-registrar
          image: gcr.io/spiffe-io/wait-for-it
          args:
            - "-t"
            - "30"
            - "registrar:8444"
      containers:
        - name: agent
          image: {{ .Values.agent.image }}
          args:
            - "-config"
            - "/run/spire/config/agent.conf"
          volumeMounts:
            - name: agent-config
              mountPath: /run/spire/config
              readOnly: true
            - name: agent-socket
              mountPath: /run/spire/socket
              readOnly: false
            - name: server-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: agent-token
              mountPath: /run/spire/token
              readOnly: false
          livenessProbe:
            exec:
              command:
                - /opt/spire/bin/spire-agent
                - healthcheck
                - -socketPath
                - /run/spire/socket/agent.sock
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
      volumes:
        - name: agent-config
          configMap:
            name: agent-config
        - name: agent-socket
          hostPath:
            path: /run/spire/socket
            type: DirectoryOrCreate
        - name: server-bundle
          configMap:
            name: server-bundle
        - name: agent-token
          projected:
            sources:
              - serviceAccountToken:
                  path: agent
                  expirationSeconds: 7200
                  audience: server