apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.gmControlApi.name}}-init
spec:
  template:
    metadata:
      name: {{.Values.gmControlApi.name}}-init
    spec:
      restartPolicy: "OnFailure"
      # We need a SA with read access to the `Endpoints` resource
      serviceAccountName: {{ .Values.global.waiter.serviceAccount.name }}
      initContainers:
        - name: ensure-gm-control-api
          image: deciphernow/k8s-waiter
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: {{ .Values.gmControlApi.name }}
      containers:
        - image: {{ tpl .Values.gmControlApi.init.image . }}
          name: {{ .Values.gmControlApi.name }}-init
          imagePullPolicy: {{ .Values.gmControlApi.init.imagePullPolicy }}
          command: ["/tmp/bootstrap/bootstrap.sh"]
          env:
          {{- include "envvars" (dict "envvar" .Values.gmControlApi.init.envvars "top" $) | indent 12 }}
          volumeMounts:
          {{- range $name, $service := .Values.global.services }}
            - name: service-config-volume-{{$service.serviceName}}
              mountPath: /etc/config/mesh/services/{{$service.serviceName}}
            - name: edge-config-volume-{{$service.serviceName}}
              mountPath: /etc/config/mesh/edge/{{$service.serviceName}}
          {{- end }}
            - name: special-config-volume
              mountPath: /etc/config/mesh/special
            - name: bootstrap-script-volume
              mountPath: /tmp/bootstrap
      volumes:
        {{- range $name, $service := .Values.global.services }}
        - name: service-config-volume-{{ $service.serviceName }}
          configMap:
            name: service-{{ $service.serviceName }}-mesh-config
        - name: edge-config-volume-{{ $service.serviceName }}
          configMap:
            name: edge-{{ $service.serviceName }}-mesh-config
        {{- end }}
        - name: bootstrap-script-volume
          configMap:
            name: bootstrap-script
            defaultMode: 0777
        - name: special-config-volume
          configMap:
            name: special-mesh-config
      imagePullSecrets:
        - name: docker.secret