kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      gm.proxy: catalog
      deployment: catalog
  replicas: 1
  template:
    metadata:
      labels:
        gm.proxy: catalog
        deployment: catalog
    spec:
      serviceAccountName: {{ .Values.global.waiter.service_account.name }}
      initContainers:
        - name: ensure-gm-control
          image: {{ .Values.global.waiter.image }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: control
            - name: POST_DELAY
              value: "10"
      containers:
      - name: catalog
        image: {{ tpl .Values.catalog.image $ }}
        imagePullPolicy: {{ .Values.catalog.image_pull_policy }}
        {{- if .Values.catalog.resources }}
        resources:
{{ toYaml .Values.catalog.resources | indent 12 }}
        {{- end }}
        env:
        {{- include "envvars" (dict "envvar" .Values.catalog.envvars "top" $) | indent 10 }}
        {{- if .Values.catalog.secret }}
        volumeMounts:
          - name: certs
            mountPath: {{ .Values.catalog.secret.mount_point }}
        {{- end }}
      - name: sidecar
        image: {{ tpl $.Values.sidecar.image $ }}
        imagePullPolicy: {{ .Values.sidecar.image_pull_policy }}
        {{- if .Values.sidecar.resources }}
        resources:
{{ toYaml .Values.sidecar.resources | indent 12 }}
        {{- end }}
        ports:
          - name: proxy
            containerPort: {{ .Values.sidecar.port }}
          - name: metrics
            containerPort: {{ .Values.sidecar.metrics_port }}
        env:
        {{- include "sidecar.envvars" $ | indent 10 }}
        volumeMounts:
        {{- if .Values.sidecar.secret.enabled }}
        {{- include "sidecar_volume_certs_mount" . | indent 10 }}
        {{- end }}
        {{- if .Values.global.spire.enabled }}
        {{- include "spire_volume_mount" . | indent 10 }}
        {{- end }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "curl -k --cacert {{ .Values.sidecar.secret.mount_point }}/{{ .Values.sidecar.secret.secret_keys.ca }} --key  {{ .Values.sidecar.secret.mount_point }}/{{ .Values.sidecar.secret.secret_keys.key }} --cert  {{ .Values.sidecar.secret.mount_point }}/{{ .Values.sidecar.secret.secret_keys.cert }} https://localhost:9080/summary"
          initialDelaySeconds: 20
          periodSeconds: 5
      {{- if .Values.global.consul.enabled }}
      {{- $data := dict "Values" .Values "ServiceName" "catalog" }}
      {{- include "consul.agent" $data | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.global.consul.enabled }}
      - name: data-consul
        emptyDir: {}
      - name: config-consul
        emptyDir: {}
      {{- end }}
      {{- if .Values.sidecar.secret.enabled }}
      {{- include "sidecar_certs_volumes" . | indent 6 }}
      {{- end }}
      {{- if .Values.global.spire.enabled }}
      {{- include "spire_volumes" . | indent 6 }}
      {{- end }}
      {{- if .Values.catalog.secret }}
      - name: certs
        secret:
          secretName: {{ .Values.catalog.secret.secret_name }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.global.image_pull_secret }}
