apiVersion: v2
appVersion: 1.2.0
description: A Helm chart to deploy the Spire Server
name: server
version: 2.2.2
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: greymatter-io
    email: engineering@greymatter.io
keywords:
  - Grey Matter
  - service mesh
  - spire
  - server
